### PR TITLE
Top10temp

### PR DESCRIPTION
**Pull request by IcyPalm**
A little more prettier layout for the measurements

### CODE REVIEW

**Comment by IcyPalm** [comment]
@goto-bus-stop you can take a look if you are satisfied, then: merge

**Comment by goto-bus-stop** [comment]
Could we show the station name / country instead of ID?

**Comment by goto-bus-stop** [comment]
`title_case($station->name)`, of course

**Comment by IcyPalm** [comment]
#fixed :+1:

**Pull request merged**
