### PR TITLE
Set up Bootstrap 4 & Babel compilation using Gulp

### PR DESCRIPTION
**Pull request by goto-bus-stop**
`gulp sass` → compile `resources/assets/sass` to `public/style/app.css`

Using bootstrap 4 because #yolo

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
#minifiers #yolo

**Comment by goto-bus-stop** [comment]
#minifiers #yolo

**Comment by IcyPalm** [comment]
Whatwhatwhat

**Comment by tieskedh** [comment]
@IcyPalm Just another test

**Comment by IcyPalm** [comment]
@IcyPalm Dus zo :)

**Comment by Jarinus** [comment]
@tieskedh Lelelele

**Pull request merged**
